# Generated by Django 3.2.7 on 2021-10-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan_Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=1)),
                ('interest_rate', models.IntegerField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
            ],
        ),
    ]
