# Generated by Django 3.2.7 on 2021-10-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_fund',
            name='taken',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
