# Generated by Django 3.2.7 on 2021-10-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loan_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan1',
            name='taken',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan_fund',
            name='taken',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
