# Generated by Django 3.2.7 on 2021-10-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_auto_20211007_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_template',
            name='payments_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
