# Generated by Django 3.2.7 on 2021-10-07 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_loan_template_payments_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lona_to_Loan_Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loan1')),
                ('loan_fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loan_fund')),
            ],
        ),
    ]
