# Generated by Django 3.2.7 on 2021-10-07 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_lona_to_loan_fund'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lona_to_Loan_Fund',
            new_name='Loan_to_Loan_Fund',
        ),
    ]
