# Generated by Django 3.2.7 on 2021-10-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_rename_lona_to_loan_fund_loan_to_loan_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_to_loan_fund',
            name='pmt_out',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='loan_to_loan_fund',
            unique_together={('loan', 'loan_fund')},
        ),
    ]
